# Generated by Django 5.0 on 2023-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
