# Generated by Django 5.0 on 2023-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_shoppinglist_items_shoppinglist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='ie date or name of function this list is for', max_length=100),
        ),
    ]
